apiVersion: batch/v1
kind: CronJob
metadata:
  name: publish-elephant-seal-fact
spec:
  schedule: "15 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.79.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -ec
            - curl -XPOST facts-api:3080/animals/elephant-seal/publish -v
          restartPolicy: OnFailure
