// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: facts.proto

package facts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fact int64 `protobuf:"varint,1,opt,name=Fact,proto3" json:"Fact,omitempty"`
}

func (x *FactID) Reset() {
	*x = FactID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_facts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactID) ProtoMessage() {}

func (x *FactID) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactID.ProtoReflect.Descriptor instead.
func (*FactID) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{0}
}

func (x *FactID) GetFact() int64 {
	if x != nil {
		return x.Fact
	}
	return 0
}

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fact string `protobuf:"bytes,1,opt,name=Fact,proto3" json:"Fact,omitempty"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_facts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_facts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_facts_proto_rawDescGZIP(), []int{1}
}

func (x *Fact) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

var File_facts_proto protoreflect.FileDescriptor

var file_facts_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x61, 0x63, 0x74, 0x73, 0x22, 0x1c, 0x0a, 0x06, 0x46, 0x61, 0x63, 0x74, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x46, 0x61,
	0x63, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x61,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x61, 0x63, 0x74, 0x32, 0x31,
	0x0a, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x61, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x46, 0x61,
	0x63, 0x74, 0x1a, 0x0d, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x49,
	0x44, 0x42, 0x2e, 0x5a, 0x2c, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x6f, 0x6f, 0x79, 0x65, 0x6e, 0x2f, 0x61,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2d, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_facts_proto_rawDescOnce sync.Once
	file_facts_proto_rawDescData = file_facts_proto_rawDesc
)

func file_facts_proto_rawDescGZIP() []byte {
	file_facts_proto_rawDescOnce.Do(func() {
		file_facts_proto_rawDescData = protoimpl.X.CompressGZIP(file_facts_proto_rawDescData)
	})
	return file_facts_proto_rawDescData
}

var file_facts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_facts_proto_goTypes = []interface{}{
	(*FactID)(nil), // 0: facts.FactID
	(*Fact)(nil),   // 1: facts.Fact
}
var file_facts_proto_depIdxs = []int32{
	1, // 0: facts.facts.CreateFact:input_type -> facts.Fact
	0, // 1: facts.facts.CreateFact:output_type -> facts.FactID
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_facts_proto_init() }
func file_facts_proto_init() {
	if File_facts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_facts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_facts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_facts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facts_proto_goTypes,
		DependencyIndexes: file_facts_proto_depIdxs,
		MessageInfos:      file_facts_proto_msgTypes,
	}.Build()
	File_facts_proto = out.File
	file_facts_proto_rawDesc = nil
	file_facts_proto_goTypes = nil
	file_facts_proto_depIdxs = nil
}
