// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FactsClient is the client API for Facts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FactsClient interface {
	PublishFact(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error)
}

type factsClient struct {
	cc grpc.ClientConnInterface
}

func NewFactsClient(cc grpc.ClientConnInterface) FactsClient {
	return &factsClient{cc}
}

func (c *factsClient) PublishFact(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error) {
	out := new(PublishReply)
	err := c.cc.Invoke(ctx, "/Facts/PublishFact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactsServer is the server API for Facts service.
// All implementations must embed UnimplementedFactsServer
// for forward compatibility
type FactsServer interface {
	PublishFact(context.Context, *PublishRequest) (*PublishReply, error)
	mustEmbedUnimplementedFactsServer()
}

// UnimplementedFactsServer must be embedded to have forward compatible implementations.
type UnimplementedFactsServer struct {
}

func (UnimplementedFactsServer) PublishFact(context.Context, *PublishRequest) (*PublishReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishFact not implemented")
}
func (UnimplementedFactsServer) mustEmbedUnimplementedFactsServer() {}

// UnsafeFactsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactsServer will
// result in compilation errors.
type UnsafeFactsServer interface {
	mustEmbedUnimplementedFactsServer()
}

func RegisterFactsServer(s grpc.ServiceRegistrar, srv FactsServer) {
	s.RegisterService(&Facts_ServiceDesc, srv)
}

func _Facts_PublishFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactsServer).PublishFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Facts/PublishFact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactsServer).PublishFact(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Facts_ServiceDesc is the grpc.ServiceDesc for Facts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Facts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Facts",
	HandlerType: (*FactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishFact",
			Handler:    _Facts_PublishFact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publisher.proto",
}
