name: Build subscriptions

on:
  push:
    paths:
      - 'subscriptions/**'
      - '.github/workflows/subscriptions.yml'
  pull_request:
    paths:
      - 'subscriptions/**'
      - '.github/workflows/subscriptions.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/subscriptions
  BUILD_VERSION: 0.0.1
  BUILD_DATE_VAR: github.com/snooyen/animal-facts/subscriptions/pkg/version.BuildDate
  BUILD_VERSION_VAR: github.com/snooyen/animal-facts/subscriptions/pkg/version.BuildVersion

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d-%H:%M)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./subscriptions/
          build-args: |
            "LDFLAGS=-X ${{ env.BUILD_DATE_VAR }}=${{ steps.date.outputs.date }} -X ${{ env.BUILD_VERSION_VAR }}=${{ env.BUILD_VERSION }}"
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max